version: '3'
services:
  puisiku-rest-db:
    image: postgres
    env_file:
      - .env
    hostname: ${PSQL_HOST}
    environment:
      POSTGRES_DB: ${PSQL_NAME}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - '5434:${PSQL_PORT}'
    volumes:
      - puisiku_rest_volume:/var/lib/postgresql/data
    networks:
      - puisiku
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER} -d ${PSQL_NAME} -h ${PSQL_HOST} -p ${PSQL_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  puisiku-rest-cache:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - puisiku

  puisiku-rest-service:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      puisiku-rest-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${PSQL_USER}:${PSQL_PASSWORD}@${PSQL_HOST}:${PSQL_PORT}/${PSQL_NAME}
      - REDIS_URL=redis://cache:6379
    command: sh -c "npx prisma migrate deploy && npm run start"
    volumes:
      - puisiku_public_rest_volume:/app/public
    networks:
      - puisiku
    restart: on-failure:5

volumes:
  puisiku_rest_volume:
  puisiku_public_rest_volume:

networks:
  puisiku:
    external: true
