version: '3'
services:
  puisiku-rest-db:
    image: postgres
    env_file:
      - .env
    hostname: ${PSQL_HOST}
    environment:
      POSTGRES_DB: ${PSQL_NAME}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - '5434:${PSQL_PORT}'
    volumes:
      - puisiku_rest_volume:/var/lib/postgresql/data

  puisiku-rest-cache:
    image: redis:latest

  puisiku-rest-service:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - puisiku-rest-db
      - puisiku-rest-cache
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${PSQL_USER}:${PSQL_PASSWORD}@${PSQL_HOST}:${PSQL_PORT}/${PSQL_NAME}
      - REDIS_URL=redis://cache:6379
    command: sh -c "npx prisma migrate deploy && npm run start"
    volumes:
      - puisiku_public_rest_volume:/app/public

volumes:
  puisiku_rest_volume:
  puisiku_public_rest_volume:
