export const poems = [
    {
      title: 'The Journey',
      creatorId: 1,
      genre: 'Adventure',
      content: 'Once upon a time...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2023,
      albumId: 1,
    },
    {
      title: 'Love Sonnet',
      creatorId: 2,
      genre: 'Romantic',
      content: 'Roses are red...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2022,
      albumId: 2,
    },
    {
      title: 'The Lost City',
      creatorId: 3,
      genre: 'Mystery',
      content: 'In the depths of the forest...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2024,
      albumId: 3,
    },
    {
      title: 'Winter Breeze',
      creatorId: 4,
      genre: 'Nature',
      content: 'Amidst the frozen lake...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2021,
      albumId: 4,
    },
    {
      title: 'The Last Stand',
      creatorId: 5,
      genre: 'Action',
      content: 'As the battle raged on...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2025,
      albumId: 5,
    },
    {
      title: 'Sunset Serenade',
      creatorId: 6,
      genre: 'Romantic',
      content: 'Under the orange sky...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2022,
      albumId: 6,
    },
    {
      title: 'Whispers in the Wind',
      creatorId: 7,
      genre: 'Mystery',
      content: 'In the eerie night...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2023,
      albumId: 7,
    },
    {
      title: 'The Enchanted Forest',
      creatorId: 8,
      genre: 'Fantasy',
      content: 'Where fairies danced...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2024,
      albumId: 8,
    },
    {
      title: 'Echoes of the Past',
      creatorId: 9,
      genre: 'Drama',
      content: 'Amidst the ruins...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2023,
      albumId: 9,
    },
    {
      title: 'City Lights',
      creatorId: 10,
      genre: 'Urban',
      content: 'In the heart of the metropolis...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2025,
      albumId: 10,
    },
    {
      title: 'Wonderful',
      creatorId: 1,
      genre: 'Nature',
      content: 'Its like snow on the ground...',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2023,
      albumId: 1,
    },
    {
      title: 'Ten',
      creatorId: 1,
      genre: 'Eligi',
      content: 'Now that i clicked, im gonna risk it..',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2023,
      albumId: 2,
    },
    {
      title: 'New Romantic',
      creatorId: 1,
      genre: 'Romantics',
      content: 'Build a castle..',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2023,
      albumId: 2,
    },
    {
      title: 'Gone',
      creatorId: 1,
      genre: 'Eligi',
      content: 'I think im finally clean..',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2023,
      albumId: 1,
    },
    {
      title: 'Clean',
      creatorId: 1,
      genre: 'Patriot',
      content: 'The rain came pouring down..',
      imagePath: '/img/default_poem.jpg',
      audioPath: '/audio/default_audio.mp3',
      year: 2023,
      albumId: 1,
    },
  ];
