export const poems = [
    {
      title: 'The Journey',
      creatorId: 1,
      genre: 'Adventure',
      content: 'Once upon a time...',
      imagePath: '/path/to/image1',
      audioPath: '/path/to/audio1',
      year: 2023,
      albumId: 1,
    },
    {
      title: 'Love Sonnet',
      creatorId: 2,
      genre: 'Romantic',
      content: 'Roses are red...',
      imagePath: '/path/to/image2',
      audioPath: '/path/to/audio2',
      year: 2022,
      albumId: 2,
    },
    {
      title: 'The Lost City',
      creatorId: 3,
      genre: 'Mystery',
      content: 'In the depths of the forest...',
      imagePath: '/path/to/image3',
      audioPath: '/path/to/audio3',
      year: 2024,
      albumId: 3,
    },
    {
      title: 'Winter Breeze',
      creatorId: 4,
      genre: 'Nature',
      content: 'Amidst the frozen lake...',
      imagePath: '/path/to/image4',
      audioPath: '/path/to/audio4',
      year: 2021,
      albumId: 4,
    },
    {
      title: 'The Last Stand',
      creatorId: 5,
      genre: 'Action',
      content: 'As the battle raged on...',
      imagePath: '/path/to/image5',
      audioPath: '/path/to/audio5',
      year: 2025,
      albumId: 5,
    },
    {
      title: 'Sunset Serenade',
      creatorId: 6,
      genre: 'Romantic',
      content: 'Under the orange sky...',
      imagePath: '/path/to/image6',
      audioPath: '/path/to/audio6',
      year: 2022,
      albumId: 6,
    },
    {
      title: 'Whispers in the Wind',
      creatorId: 7,
      genre: 'Mystery',
      content: 'In the eerie night...',
      imagePath: '/path/to/image7',
      audioPath: '/path/to/audio7',
      year: 2023,
      albumId: 7,
    },
    {
      title: 'The Enchanted Forest',
      creatorId: 8,
      genre: 'Fantasy',
      content: 'Where fairies danced...',
      imagePath: '/path/to/image8',
      audioPath: '/path/to/audio8',
      year: 2024,
      albumId: 8,
    },
    {
      title: 'Echoes of the Past',
      creatorId: 9,
      genre: 'Drama',
      content: 'Amidst the ruins...',
      imagePath: '/path/to/image9',
      audioPath: '/path/to/audio9',
      year: 2023,
      albumId: 9,
    },
    {
      title: 'City Lights',
      creatorId: 10,
      genre: 'Urban',
      content: 'In the heart of the metropolis...',
      imagePath: '/path/to/image10',
      audioPath: '/path/to/audio10',
      year: 2025,
      albumId: 10,
    },
  ];
