export const users = [
    {
      name: 'John Doe',
      email: 'johndoe@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      name: 'Jane Smith',
      email: 'janesmith@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      name: 'Michael Johnson',
      email: 'michaeljohnson@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      name: 'Emily Davis',
      email: 'emilydavis@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      name: 'William Wilson',
      email: 'williamwilson@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      name: 'Olivia Jones',
      email: 'oliviajones@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      name: 'Daniel Anderson',
      email: 'danielanderson@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      name: 'Sophia Martinez',
      email: 'sophiamartinez@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      name: 'Alexis Taylor',
      email: 'alexistaylor@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      name: 'James Thomas',
      email: 'jamesthomas@example.com',
      hashedPassword: '$2b$10$uIrD6qdnlDli7a/0YK3ZA.v/WG.f8mZ3ivOaCJikD9f6h00x7YaUK',
      imagePath: '/img/1699444402604_3.png',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
  ];